modules/client-browser/package.json
modules/client-node/package.json
modules/integration-browser/package.json

* client-node remove bin
* client-browser remove bin
* integration-browser add build_fixtures to files

fix: package.json issues

---

modules/material-management/src/cryptographic_material.ts

Older js engines require this. See https://stackoverflow.com/a/21624550

fix: Always explicitly catch exceptions.

---

modules/web-crypto-backend/test/fixtures.ts
modules/web-crypto-backend/test/promisify-ms-crypto.test.ts
modules/web-crypto-backend/test/synchronous_random_values.test.ts

More complete tests with stubs

fix: web-crypto-backend testing

---

modules/raw-aes-keyring-node/src/raw_aes_keyring_node.ts
modules/raw-aes-keyring-node/test/raw_aes_keyring_node.test.ts

test: Condition tests for raw-aes-keyring-node

---

package.json

The proper script should be called

fix: test_conditions should execute the script

---

CONTRIBUTING.md

Organize the links and add conventional commits requirement for PRs

doc: Update contributing doc

---

README.md

doc: This project is generally available

---

modules/client-browser/package.json
modules/client-node/package.json
package.json

*Issue #, if available:* https://github.com/aws/aws-encryption-sdk-javascript/issues/225
*Description of changes:* Added keywords to manifest to improve npm searchability.

Add keywords field to package.json

---

modules/cache-material/README.md
modules/kms-keyring/README.md
modules/material-management/README.md
modules/raw-keyring/README.md
modules/serialize/README.md
modules/web-crypto-backend/README.md

The package referred to in each Readme.md is singular.

docs: Update Readme, package is singular

---

package-lock.json
package.json

fix: update package.lock and package.json format

---

modules/caching-materials-manager-browser/package-lock.json
modules/caching-materials-manager-browser/package.json
modules/decrypt-browser/package-lock.json
modules/decrypt-browser/package.json
modules/encrypt-browser/package-lock.json
modules/encrypt-browser/package.json
modules/example-browser/package.json
modules/integration-browser/package-lock.json
modules/integration-browser/package.json
modules/kms-keyring-browser/package-lock.json
modules/kms-keyring-browser/package.json
modules/material-management-browser/package-lock.json
modules/material-management-browser/package.json
modules/raw-aes-keyring-browser/package-lock.json
modules/raw-aes-keyring-browser/package.json
modules/raw-rsa-keyring-browser/package-lock.json
modules/raw-rsa-keyring-browser/package.json
modules/web-crypto-backend/package-lock.json
modules/web-crypto-backend/package.json
package-lock.json
package.json

The crypto-helpers and the AWS SDK v3 was bumped to alpha.

feat: Update version of dependencies 

---

modules/client-node/Readme.md

Fix sample code in some documentation.

docs: fix sample code in client-node/Readme.md

---

package-lock.json
package.json

*Description of changes:* Upgrade to lerna 4.0.0.

chore: Upgrade dev dependencies to use to lerna 4.0.0

---

.gitmodules
package.json

chore: Update submodules

---

modules/material-management-node/src/material_helpers.ts
package-lock.json
package.json

Issue #722 
Updated @types/node to 16.7.8
Renamed `Signer` to `Sign`

fix: Update @types/node to 16.7.9

---

modules/material-management-node/src/material_helpers.ts
package-lock.json
package.json

This reverts commit 7ba9425166ce0adc5feda67415e514f4d5616b87.
*Issue #, if available:* See comments on #723
*Description of changes:* Rollback breaking change.

fix: Revert #7ba9425166ce0adc5feda67415e514f4d5616b87

---

modules/example-browser/package.json
package-lock.json

chore: update dependencies

---

modules/example-node/Readme.md

Update Readme to include a note to run `nom build` for the whole project
Fixes: #948

chore: Update example-node instructions

---

codebuild/release/prod-release.yml

chore: remove node10 from test

---

modules/kms-keyring-node/package.json
modules/kms-keyring-node/src/kms_mrk_strict_multi_keyring_node.ts

*Issue # 922*
Added material-management as a dependency of kms-keyring-node

chore: add material-management as a dependency of kms-keyring-node

---

modules/kms-keyring-browser/package.json
modules/kms-keyring-node/package.json
modules/material-management/src/algorithm_suites.ts
package-lock.json

chore: bump aws-sdk to >= 2.1360.0

---

codebuild/release/prod-release.yml

chore: update image for version and publish

---

.github/dependabot.yml

chore: Add groups to dependabot config

---

modules/caching-materials-manager-browser/package.json
modules/example-browser/package.json
modules/material-management-browser/package.json
modules/raw-rsa-keyring-browser/package.json
package-lock.json
package.json

chore: update package-lock.json

---

.github/workflows/ci.yml

chore(CI): add coverage browser tests to CI

---

codebuild/nodejs20.yml

chore: update iam permissions for static tv

---

modules/material-management/package.json
package-lock.json

fix: include uuid as a dependency in material-management
