modules/integration-browser/karma.conf.js
modules/integration-browser/package.json

Integration-browser should be able to be installed from npm
and just work.
* include karma.config.js in package
* karma and friends are dependencies, not a devDependencies
* webpack the js files, not the typescript files

fix: integration-browser should work from npm

---

modules/material-management/src/cryptographic_material.ts
modules/material-management/src/signature_key.ts
modules/material-management/src/types.ts
modules/raw-keyring/src/raw_aes_material.ts

resolves #137
Cryptographic materials need to understand CryptoKeys
to insure that a given algorithm suite is satisfied.
However, by exporting the DOM types in function calls,
all dependent modules must import DOM types.
This pollution is not needed,
especially for node packages.
Pull the type structure into the module and export
that interface.
Update raw_aes_materials to use new types.

fix: material-management should not export DOM types

---

modules/decrypt-node/src/decipher_stream.ts
modules/decrypt-node/src/verify_stream.ts
modules/encrypt-node/src/framed_encrypt_stream.ts
modules/material-management-node/src/index.ts
modules/material-management-node/src/material_helpers.ts
modules/raw-rsa-keyring-node/src/raw_rsa_keyring_node.ts

resolves #135
The AWS Encryption SDK should track the Node.js LTS policy.
For developers using Typescript and @types/node@8
the ESDK should “just work”.
Because some packages export Node.js types like `CipherGCM`
developers would be forced to install an unwanted type version.
This pulls in the needed parts of the needed types into the packages.
It is only the types that differ in this case.
Regarding KeyObjects, rsa support is removed,
but will be added back in when #74 is addressed.

feat: Node.js Typescript version dependency

---

modules/kms-keyring-node/src/kms_keyring_node.ts
modules/kms-keyring/package.json
modules/kms-keyring/src/helpers.ts
modules/kms-keyring/src/kms_client_supplier.ts
modules/kms-keyring/src/kms_keyring.ts
modules/kms-keyring/src/kms_types.ts

resolves #136
resolved #138
The AWS SDK for JS v2 and v3 have similar types,
but they are not exactly the same.
In a effort to have both versions work,
I imported as dev dependencies all the relevant packages
and tried to use conditional types.
However, since the types are all exported by the functions
this did not work as planed and caused _every_ client to want _every_ SDK.
The interface the AWS Encryption SDK for JS needs
from the AWS SDK is minimal.
Hand rolling the appropriate types is the best solution at this time.

fix: aws sdk version dependencies pollution

---

modules/encrypt-browser/src/encrypt.ts
modules/encrypt-browser/test/encrypt.test.ts
modules/encrypt-node/src/encrypt_stream.ts
modules/encrypt-node/test/encrypt.test.ts

resolves #129
The other ESDK’s use frameLength === 0 to indicate non-framed content.
The JS ESDK does not support encrypting non-framed content.
A frameLength of 0 will crash the process.
Add condition and test.

fix: frame length can not be 0

---

modules/integration-node/package.json
modules/integration-node/src/cli.ts
modules/integration-node/src/decrypt_materials_manager_node.ts
modules/integration-node/src/get_decrypt_test_iterator.ts
modules/integration-node/src/get_encrypt_test_iterator.ts
modules/integration-node/src/index.ts
modules/integration-node/src/integration_tests.ts
modules/integration-node/src/types.ts
package.json

https://github.com/awslabs/aws-crypto-tools-test-vector-framework defines an encryption manifest.
This manifest should be used to maintain cross compatibility of language implementations.
Then integrate this into the CI integration tests.

feat: Encryption tests for integration-node

---

modules/encrypt-browser/src/encrypt.ts
modules/encrypt-browser/test/encrypt.test.ts
modules/encrypt-node/test/encrypt.test.ts

resolves #155
Browser encrypt did not break up the plaintext buffer for each frame.
It needs to break up the plaintext and identify the correct length in
the messageAAD

fix: browser framed encryption

---

modules/integration-node/src/decrypt_materials_manager_node.ts
modules/integration-node/src/get_decrypt_test_iterator.ts
modules/integration-node/src/get_encrypt_test_iterator.ts
modules/integration-node/src/types.ts
modules/integration-node/test/decrypt_materials_manager_node.test.ts
modules/integration-node/test/get_decrypt_test_iterator.test.ts
modules/integration-node/test/get_encrypt_test_iterator.test.ts

Basic tests for integration-node

test: Adding test for integration-node

---

modules/integration-browser/karma.conf.js
modules/integration-browser/package.json
modules/integration-browser/src/build_decrypt_fixtures.ts
modules/integration-browser/src/build_encrypt_fixtures.ts
modules/integration-browser/src/cli.ts
modules/integration-browser/src/decrypt_materials_manager_web_crypto.ts
modules/integration-browser/src/integration.decrypt.test.ts
modules/integration-browser/src/integration.encrypt.test.ts
modules/integration-browser/src/types.ts
package.json

https://github.com/awslabs/aws-crypto-tools-test-vector-framework defines an encryption manifest.
This manifest should be used to maintain cross compatibility of language implementations.
Then integrate this into the CI integration tests.
Also update package.json to better organize parameters.

feat: Encryption tests for integration-browser

---

modules/caching-materials-manager-node/src/caching_materials_manager_node.ts
modules/caching-materials-manager-node/src/sha512.ts
modules/caching-materials-manager-node/test/caching_materials_manager_node.test.ts
modules/caching-materials-manager-node/test/sha512.test.ts

Simple refactor to better test the node caching CMM

test: Testing cacheing CMM

---

modules/material-management/src/multi_keyring.ts
modules/material-management/test/multi_keyring.test.ts

If a multi keyring did not have a generator,
but was passed material with an unencrypted data key,
it would throw.
This is incorrect.
Better code, tests, and error messages.

fix: Multi keyrings should not require a generator

---

buildspec.yml
package.json
util/test_conditions

Offer a way to override issues
Integrate into CI
The purpose here is to make sure that for every `Precondition` or `Postcondition` there exists a test.

fix: update test_conditions to beter report

---

.gitmodules
modules/integration-browser/karma.conf.js
modules/integration-browser/src/cli.ts
package.json

* add no-sandbox to integration-browser
see: https://bugs.chromium.org/p/chromium/issues/detail?id=638180
* Update submodule to use https
* change the names on integration to only run all tests once

fix: CI encrypt/decrypt test vectors

---

modules/integration-browser/src/build_decrypt_fixtures.ts
modules/integration-browser/src/build_encrypt_fixtures.ts
modules/integration-browser/src/cli.ts
modules/integration-node/src/cli.ts

The cli’s for the integration packages could silently error.
The logic is wrapped in an immediately invoked function expression.
The function is async, and if there is an error
this results in an unhandled promise rejection.
Catch the error, log, and exit with a non-zero code.
I also cleaned up some of the path expressions,
and removed the ts-ignore.

fix: integration silent errors

---

modules/cache-material/src/caching_cryptographic_materials_decorators.ts
modules/cache-material/test/caching_cryptographic_materials_decorators.test.ts

It is possible for material that is created in the caching CMM to immediately exceed the caching limits. In this case the materials clearly should not be cached, but also they should not be cloned.

fix: cloned material that exceeds limits

---

modules/material-management-browser/src/browser_cryptographic_materials_manager.ts
modules/material-management-browser/test/browser_cryptographic_materials_manager.test.ts
modules/material-management-node/src/node_cryptographic_materials_manager.ts
modules/material-management-node/test/node_cryptographic_materials_manager.test.ts

A CryptographicMaterialsManager can change entries to the encryptionContext
but changing these values has consequences.
The DefaultCryptographicMaterialsManager uses the value in the encryption context
to store public signing key.
If the caller is using this value in their encryption context the Default CMM
is probably not the CMM they want to use.

fix: ENCODED_SIGNER_KEY in encryption context

---

modules/cache-material/src/caching_cryptographic_materials_decorators.ts
modules/cache-material/src/index.ts
modules/kms-keyring-node/test/kms_keyring_node.test.ts
modules/kms-keyring/src/kms_keyring.ts
modules/material-management-browser/src/index.ts
modules/material-management-browser/src/material_helpers.ts
modules/material-management-node/src/index.ts
modules/material-management-node/src/material_helpers.ts
modules/material-management-node/test/material_helpers.test.ts
modules/material-management/src/clone_cryptographic_material.ts
modules/material-management/src/cryptographic_material.ts
modules/material-management/src/index.ts
modules/material-management/src/types.ts
modules/material-management/test/clone_cryptographic_material.test.ts
modules/material-management/test/cryptographic_material.test.ts
modules/material-management/test/multi_keyring.test.ts
modules/raw-aes-keyring-browser/src/raw_aes_keyring_browser.ts
modules/raw-aes-keyring-node/src/raw_aes_keyring_node.ts
modules/raw-aes-keyring-node/test/raw_aes_keyring_node.test.ts
modules/raw-keyring/src/raw_aes_material.ts
modules/raw-keyring/test/raw_keyring_decorators.test.ts
modules/raw-rsa-keyring-browser/src/raw_rsa_keyring_web_crypto.ts
modules/raw-rsa-keyring-node/src/raw_rsa_keyring_node.ts
modules/raw-rsa-keyring-node/test/raw_rsa_keyring_node.test.ts

resolves #74
KeyObjects were introduced in Node.js v11.
They wrap the Buffer in an object that has
even better security properties than an isolated buffer.

feat: Suport Node.js crypto KeyObjects

---

modules/cache-material/src/caching_cryptographic_materials_decorators.ts
modules/serialize/src/identifiers.ts

Maximum number of bytes which are allowed to be encrypted under a single data key
The _real_ maximum is 2 ** 63 - 1,
However Javascript can only perform safe operations on values
up to Number.MAX_SAFE_INTEGER === 9007199254740991 === 2 ** 53 - 1.
e.g
Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2 => true
Number.MAX_SAFE_INTEGER + 1 > Number.MAX_SAFE_INTEGER + 2 => false
Number.MAX_SAFE_INTEGER + 1 < Number.MAX_SAFE_INTEGER + 2 => false
This means that after 2 ** 53 - 1 the process of accumulating a byte count
will never yield an accurate comparison and so, never halt.
The choice here to use 2 ** 53 - 1 instead of Number.MAX_SAFE_INTEGER is deliberate.
This is because in the future Number.MAX_SAFE_INTEGER could be raised to 2 ** 66
or some value larger 2 ** 63.
By submitting …

fix: BYTES_PER_KEY value

---

modules/material-management/src/cryptographic_material.ts
modules/material-management/test/cryptographic_material.test.ts
modules/raw-keyring/src/raw_aes_material.ts

It is a feature that is not being used.
This was created to let callers confirm that the unencrypted data key matched the algorithm suite,
but this checking is done directly into the cryptographic material now.
The `hasUnencryptedDataKey` is the best way to check for existence,
and the materials themselves will ensure that algorithm suite specifications are meet.

feat: Remove unencryptedDataKeyLength

---

modules/decrypt-node/src/decipher_stream.ts

resolves #199
In Node.js versions 10.9 and older will fail to decrypt if decipher.update is not called.
https://github.com/nodejs/node/pull/22538 fixes this.
If the content is empty, push an empty buffer.

fix: Zero length frames in old version of Node

---

modules/encrypt-browser/src/encrypt.ts
modules/encrypt-browser/test/encrypt.test.ts
modules/encrypt-node/src/encrypt.ts
modules/encrypt-node/test/encrypt.test.ts
modules/example-browser/src/aes_simple.ts
modules/example-browser/src/kms_simple.ts
modules/example-browser/src/multi_keyring.ts
modules/example-browser/src/rsa_simple.ts
modules/example-node/src/aes_simple.ts
modules/example-node/src/kms_simple.ts
modules/example-node/src/multi_keyring.ts
modules/example-node/src/rsa_simple.ts
modules/integration-browser/src/integration.encrypt.test.ts
modules/integration-node/src/integration_tests.ts

Javascript stimulates named parameters with objects.
The previous version used `ciphertext` to denote
the usable result from a call to `encrypt`.
However, this caused some cogitative load.
Ciphertext is used to denote encrypted data,
however the result of a call to `encrypt` in not _only_ encrypted data.
The AWS Encryption SDK uses envelop encryption,
so the result of a call to `encrypt` include not only the encrypted data,
but also, the encrypted data keys, metadata, and the encryption context.
By returning both the `messageHeader` *and* the `ciphertext`
users are confused about what exactly was *in* `ciphertext`.
This is compounded by returning `messageHeader`
which is just a parsed version of the header
that is already returned by the result of `encrypt`
The named parameter is now call …

fix: Encrypt name to result

---

modules/serialize/src/deserialize_factory.ts
modules/serialize/src/read_element.ts
modules/serialize/test/read_elements.test.ts

The readElement function was previously not taking advantage of
the underlying data structure, which is a sequence of elements,
each of which is a sequence of fields. This resulted in several
superfluous calls to built-in functions (e.g. Array.prototype.splice).
This commit adds an additional parameter to readElement, which is
the number of fields per element, and adapts the code accordingly.
The return of readElement is now an array of arrays, which simplifies
its manipulation by the two caller functions.

fix: updating readElement to match underlying data structure

---

modules/integration-browser/Readme.md
modules/integration-node/Readme.md

Aline the documentation with the implemented cli interface.

doc: Update Readme

---

README.md
modules/decrypt-browser/CHANGELOG.md
modules/encrypt-browser/CHANGELOG.md
modules/encrypt-node/CHANGELOG.md
modules/integration-browser/CHANGELOG.md
modules/integration-node/CHANGELOG.md
modules/material-management/CHANGELOG.md

Document the breaking changes in moving from
`preview` to `1.0.0`.

doc: document breaking changes

---

VERSIONING.md

docs: Add versioning file

---

modules/example-browser/Readme.md

*Description of changes:* There was a mistake in the filename to open multi_keyring in example-browse. Fixed the issue by changing the command with correct filename. 

docs: Fixed command to open multi_keyring.html in example-browser

---

modules/material-management/src/cryptographic_material.ts

`eval` was added to help ensure that `portableTimingSafeEqual`
is not optimized into a non-constant time function.
However, the Content Security Policy `'unsafe-eval'` will flag this.
It is better to remove this and risk such an optimization,
then to force customers to weaken the Content Security Policy.

fix: eval in portableTimingSafeEqual

---

modules/material-management-browser/src/browser_cryptographic_materials_manager.ts
modules/material-management-node/src/node_cryptographic_materials_manager.ts

resolves #232
Typescript 3.7 does a better job identifying declaration conflicts
and so identifies the conflict between the type
and the class import of the same name.
e.g. `WebCryptoEncryptionMaterial` is defined as a type and imported.
When #148 was written the reference to the return type
should have gone directly to the needed Material (WebCrypto or Node).

fix: Import declaration conflicts with local declaration

---

.gitignore
modules/cache-material/package-lock.json
modules/caching-materials-manager-browser/package-lock.json
modules/caching-materials-manager-node/package-lock.json
modules/client-browser/package-lock.json
modules/client-node/package-lock.json
modules/decrypt-browser/package-lock.json
modules/decrypt-node/package-lock.json
modules/encrypt-browser/package-lock.json
modules/encrypt-node/package-lock.json
modules/example-browser/package-lock.json
modules/example-node/package-lock.json
modules/hkdf-node/package-lock.json
modules/integration-browser/package-lock.json
modules/integration-node/package-lock.json
modules/kms-keyring-browser/package-lock.json
modules/kms-keyring-node/package-lock.json
modules/kms-keyring/package-lock.json
modules/material-management-browser/package-lock.json
modules/material-management-node/package-lock.json
modules/material-management/package-lock.json
modules/raw-aes-keyring-browser/package-lock.json
modules/raw-aes-keyring-node/package-lock.json
modules/raw-keyring/package-lock.json
modules/raw-rsa-keyring-browser/package-lock.json
modules/raw-rsa-keyring-node/package-lock.json
modules/serialize/package-lock.json
modules/web-crypto-backend/package-lock.json
package-lock.json

resolves #234
Lerna version 3.18.2 will version package-lock.json files.
This means that if they are in .gitingnore the version command will fail.
Better visibility into versions should help debugging.

fix: lerna version maintains package-lock

---

modules/integration-node/src/decrypt_materials_manager_node.ts
modules/raw-rsa-keyring-node/src/index.ts
modules/raw-rsa-keyring-node/src/oaep_hash_supported.ts
modules/raw-rsa-keyring-node/src/raw_rsa_keyring_node.ts
modules/raw-rsa-keyring-node/test/raw_rsa_keyring_node.test.ts

*Issue #, if available:* #198 
AWS CloudFront Field Level Encryption uses the `RSA_OAEP_SHA256_MGF1` suite of algorithms. Because this library's raw RSA code only supports OAEP_SHA1, it can't be used to decrypt CloudFront fields.
Support for oaepHash was added in node's crypto library in node 12.9 (nodejs/node#28335), so it's possible to expose this functionality through this library now.
I've tested this manually against AWS CloudFront with Field Level Encryption set, and it seems to work nicely.
I also spotted some async test warnings, so I've done my best to clean those up. See the individual commits for more detail.

feat: Support sha256 and sha512 oaep algorithms

---

modules/integration-node/src/cli.ts
modules/integration-node/src/integration_tests.ts
package.json

Running the integration tests
can be speed up significantly by adding concurrency.
This adds a `—concurrency` and `-c` option to the cli
that can be used to run multiple tests in parallel.

feat: Add concurrency for running tests

---

modules/integration-browser/karma.conf.js
modules/integration-browser/package.json
modules/integration-browser/src/cli.ts
modules/integration-browser/src/integration.decrypt.test.ts
modules/integration-browser/src/integration.encrypt.test.ts
modules/integration-node/src/cli.ts
package-lock.json
package.json

Add a `-c` option to integration-browser
that will increase the number of browsers tested.
This speeds up the integration tests considerably.
The -c option, takes a number or the string ‘cpu’.
The string will set the concurrency
to the number of cpus - 1
This also update integration-node `-c` option to behave the same way.

Parallel integration browser

---

.gitignore
buildspec.yml
karma.conf.js
modules/caching-materials-manager-browser/karma.conf.js
modules/decrypt-browser/karma.conf.js
modules/encrypt-browser/karma.conf.js
modules/example-browser/karma.conf.js
modules/integration-browser/karma.conf.js
modules/integration-browser/package.json
modules/kms-keyring-browser/karma.conf.js
modules/material-management-browser/karma.conf.js
modules/raw-aes-keyring-browser/karma.conf.js
modules/raw-rsa-keyring-browser/karma.conf.js
modules/web-crypto-backend/karma.conf.js
package-lock.json
package.json
util/local_verdaccio_publish
util/npx_verdaccio
verdaccio/config.yaml
verdaccio/npmrc

resolves #123
To validate that everything always works,
running the integration tests directly from npm
will replicate exactly how customers would use this.
It will also verify that all dependencies of the clients
can be satisfied from npm.
Finally, it exercises the publishing process
to make sure that each release could be published automatically.

chore: add verdaccio publishing tests to CI

---

CONTRIBUTING.md
README.md

This should be at the top of the contributing page,
and should be linked at the top of the readme.

chore: Update security issue notification

---

modules/caching-materials-manager-browser/package.json

Caching materials manager browser is missing `@aws-sdk/util-utf8-browser`.
Everything generally worked because this is installed
by several other modules.
But this was a required dependency for this module in isolation.

fix: missing dependency in caching-materials-manager-browser

---

modules/integration-browser/package.json
modules/integration-browser/src/cli.ts
package-lock.json

`spawnSync` does not throw
when getting a error exit code.
`status` needs to be investigated.
Also, `@trust/keyto` was removed from dependencies.
This error was not noticed because of the above problem.

fix: integration-browser error condition

---

modules/serialize/src/decode_body_header.ts
modules/serialize/src/identifiers.ts
modules/serialize/test/decode_body_header.test.ts
modules/serialize/test/fixtures.ts

nonFramed messages are encrypted under a single operation.
The maximum number of bytes for a single AES-GCM "operation."
is 2 ** 36 - 32
This is related to the GHASH block size,
and can be thought of as the maximum bytes
that can be encrypted with a single IV.
The AWS Encryption SDK for Javascript
does not support non-framed encrypt
https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/data-format/message-body.md#non-framed-data

fix: nonFramed maximum content length

---

.github/not-grep.toml
.github/workflows/ci_static-analysis.yaml
karma.conf.js
modules/caching-materials-manager-browser/karma.conf.js
modules/decrypt-browser/karma.conf.js
modules/encrypt-browser/karma.conf.js
modules/encrypt-node/src/encrypt.ts
modules/example-browser/karma.conf.js
modules/example-browser/webpack_configs/aes.webpack.config.js
modules/example-browser/webpack_configs/caching_cmm.webpack.config.js
modules/example-browser/webpack_configs/fallback.webpack.config.js
modules/example-browser/webpack_configs/kms.webpack.config.js
modules/example-browser/webpack_configs/multi_keyring.webpack.config.js
modules/example-browser/webpack_configs/rsa.webpack.config.js
modules/integration-browser/karma.conf.js
modules/integration-browser/webpack.config.js
modules/kms-keyring-browser/karma.conf.js
modules/material-management-browser/karma.conf.js
modules/raw-aes-keyring-browser/karma.conf.js
modules/raw-rsa-keyring-browser/karma.conf.js
modules/raw-rsa-keyring-node/src/oaep_hash_supported.ts
modules/web-crypto-backend/karma.conf.js
package.json
wallaby.conf.js

This adds a GitHub Actions workflow for static analysis checks. Right now the only one is `not-grep`[1], which we're using to check for copyright headers in all source code files.
Also included are fixes for some files that we missed previously.
Run of workflow visible here[2].
[1] https://github.com/marketplace/actions/not-grep
[2] https://github.com/mattsb42-aws/aws-encryption-sdk-javascript/runs/686987225?check_suite_focus=true

chore: add GitHub Actions workflow check for copyright header and fix missing copyright headers

---

modules/material-management/src/needs.ts

TypeScript 3.7 released support for assertion functions,
that support positive assertions
that can be evaluated in TypeScript.
This updates the `needs` function to export this behavior,
so it can be used.

fix: add asserts to `needs`

---

package-lock.json
package.json

It was not being used,
and was getting deprecated.
https://github.com/aws/aws-sdk-js-v3/pull/1241
https://github.com/aws/aws-sdk-js-v3/pull/1240?

chore: remove @aws-sdk/util-utf8-universal

---

modules/material-management-browser/src/browser_cryptographic_materials_manager.ts
modules/material-management/src/types.ts

To prepare for type updates, a few more type hints are required.

fix: Update types for newer typescript versions

---

modules/kms-keyring/src/helpers.ts
modules/kms-keyring/src/kms_keyring.ts
modules/kms-keyring/test/helpers.test.ts
modules/kms-keyring/test/kms_keyring.onencrypt.test.ts

On encrypt if an AWS KMS client can not be obtained
Encrypt should HALT.
There MUST be a client for every KeyId
When a user configures a AWS KMS keyring with IDs
the intent is to be able to independently decrypt
with ANY of these IDs.
See: https://github.com/awslabs/aws-encryption-sdk-specification/blob/master/framework/kms-keyring.md#onencrypt-goal
Without a client it is
impossible to encrypt under the given CMK.
BREAKING CHANGE:
The previous behavior was to
allow the client supplier to modify
the AWS KMS KeyId intent.
This resulted in a successful
encrypt but WITHOUT the filtered KeyIds
See #317 for additional details.

fix!: The AWS Kms keyring use of clientProvider

---

buildspec.yml
codebuild/nodejs10.yml
codebuild/nodejs12.yml

Update buildspec to batch build
to run multiple Node.js runtime versions
* Node.js 10
* Node.js 12

chore: Update CI to run multiple versions of Node.js

---

modules/web-crypto-backend/src/backend-factory.ts
modules/web-crypto-backend/src/synchronous_random_values.ts
modules/web-crypto-backend/test/backend-factory.test.ts
modules/web-crypto-backend/test/synchronous_random_values.test.ts
package.json

Sinon is nice, but can not support native ES6 modules.
Because these modules are immutable on import.
Since the backen-factory and the synchronousRandomValues
function both share the same `window` object,
this can be trivially accomplished.
The other advantage is that the test are _much_ simpler.

fix: better dependency injection

---

modules/decrypt-node/src/verify_stream.ts
modules/decrypt-node/test/decrypt.test.ts

Fixes: #507
Tests exist that push a single byte at a time.
This will hit every boundary condition.
However this is not complete enough.
State can be reset as the code transitions
from one boundary condition to another.
The prime example of this problem
the `VerifyStream`.
It has 4 boundary in the `_transform` function.
The body header, the body, the auth tag, and signature.
By sending 1 byte
as the code transitions from the body header
to the body
the code handling the exiting
of the body header has no way to interact
with the body,
because the 1 byte of data
completely isolates these code branches.
In this case the code was buffering
the body header in `frameBuffer`
but when exiting this section
and passing control to
the actual content section,
it used the `chunk` to form the tail.
When …

fix: Boundary condition error in VerifyStream

---

.eslintrc.js
.gitignore
package-lock.json
package.json

*Issue #, if available:* None
*Description of changes:* Chore: Upgrade aws-sdk provided karma credentials.
The specific commands:
```
npm install @aws-sdk/credential-provider-node@latest --save-dev
npm install @aws-sdk/karma-credential-loader@latest --save-dev
npm install @aws-sdk/util-base64-browser@latest --save-dev
```

chore: upgrade dev dependencies for karma credential management

---

modules/serialize/src/decode_encryption_context.ts

If the encryption context is empty it should still be frozen.

fix: decoded encryption context is frozen

---

codebuild/release/prod-release.yml

Add codebuild spec for releasing. 
*Testing:*
I've successfully run the codebuild spec with all of the steps *except* the `npx lerna publish` command. 

Release improvements

---

codebuild/release/prod-release.yml

Node 14 isn't supported in our build image

chore: Update release codebuild to node 12

---

codebuild/release/prod-release.yml

This is merged *without* a conventional commit to continue that the 2.2.1 release process.

chore: Explicit use .npmrc for NPM_TOKEN

---

codebuild/release/prod-release.yml

If no files are updated outside of the workspaces,
then learn will not version any modules.
This feature is needed primarily for CI changes that impact customers.
Such as deprecating support and removing testing for runtime versions.

chore: explicit version bump for release

---

codebuild/release/prod-release.yml

Integration testing run in the release build was failing.
See: https://github.com/aws/aws-sdk-js/issues/3763

chore: Fix npx error

---

buildspec.yml
codebuild/release/prod-release.yml
codebuild/release/publish.yml
codebuild/release/version.yml
codebuild/test_vectors/browser.yml
codebuild/test_vectors/nodejs_latest.yml

When doing releases having the steps in parts make it easer to follow.
This also makes partial re-try simpler.
Finally, the release now shares the exact tests with CI.
So the release process is better tested

chore: break up release build

---

modules/integration-browser/package.json
package-lock.json
package.json

*Issue #, if available:* 
*Description of changes:* @aws-sdk/karma-credential-loader is private as of 3.39.0. Pin to 3.38.0 until we can move the logic into our modules and remove the dependency entirely.

fix: Pin karma-credential-loader to 3.38.0

---

modules/material-management/src/pem_helpers.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

SUPPORT_POLICY.rst
buildspec.yml
codebuild/nodejs10.yml
codebuild/release/prod-release.yml
codebuild/release/publish.yml
codebuild/release/version.yml
modules/client-browser/src/index.ts
modules/client-node/src/index.ts
modules/material-management-browser/src/index.ts
modules/material-management-node/src/index.ts
modules/material-management/src/index.ts
package.json

*Issue #, if available:* Mark 1.x as End-of-Support
- Client emits a log warning on creation detailing 1.x is in End-of-Support
- Added the support policy from master
Update Support Policy, marking:
- 1.x as EOS
- 2.x as Maintenance
- 3.x as GA
Back-ported CodeBuild NPM Publish automation.
However, the back port is not as useful as the Master version.
It does not pull the artifacts from NPM and test them after publishing.
To do that, I would need to back-port much [of this PR](https://github.com/aws/aws-encryption-sdk-javascript/pull/645/files#diff-3cf937f50c0e3ea75bb5996259a365af49f2e14274f6bcb2374c9002ebfb5d8f), which deprecates Node10. 
*Squash Commit Message*: `chore: warn 1.x is End-of-Support`
By submitting this pull request, I confirm that my contribution …

chore: Mark 1.x as End-of-Support 

---

modules/integration-browser/karma.conf.js
modules/integration-browser/package.json
modules/integration-node/package.json
package-lock.json
package.json
util/local_verdaccio_publish
util/npx_verdaccio
verdaccio/config.yaml
verdaccio/integration/Readme.md
verdaccio/integration/package.json

*Issue #, if available:* Release 1.x
Verdaccio was pulling the latest version of ESDK modules from NPM and testing thoses.
It would only test local modules if it detected changes, 
but something was wrong in the manner it detected changes.
Regardless, that is now fixed.
By back-porting changes to `util` and `verdaccio`, what ever we did on `master` to correctly 
test the ESDK with verdaccio has now been applied to mainline-1.x.
I confirmed that the local ESDK-JS's modules are being tested by inspecting verdaccio's storage:
```
ls verdaccio/storage/@aws-crypto/*/*.tgz
```
Some other fixes had to be applied:
1. Increasing the default time out for integration-browser testing
2. Fixing the `integration-browser` and `integration-node` dependence on …

fix(verdaccio): back port verdaccio fixes from master

---

codebuild/browser.yml
codebuild/nodejs_latest.yml
codebuild/test_vectors/browser.yml
codebuild/test_vectors/nodejs_latest.yml
modules/decrypt-node/test/decrypt.test.ts
package-lock.json

feat: Support Node v18

---

codebuild/release/publish.yml

Currently the release build will _always_ add the `latest` tag to every release.
If a release is for an old version,
this will result in the wrong version being tagged as `latest`.
This ENV in the build allows for proper tagging.

chore: Add dist-tag to release

---

README.md
package-lock.json

Ran the following:
```
npm install
npm audit fix
npm test
```
In general, `npm audit fix` will identify packages with security updates that can be fixed and update them along with dependencies.
In particular, this updated xml2js to `0.5.0`, which should resolve [this vulnerability](https://github.com/aws/aws-encryption-sdk-javascript/security/dependabot/46).

chore: Update package-lock.json

---

codebuild/release/publish.yml
codebuild/release/version.yml

*Issue #, if available:* CodeBuild Builds MUST USE a supported Node Version.
Replace any usage of Node 12 with Node 14 in AWS CodeBuild Builds for publishing to npm.

fix(CD): CodeBuild MUST USE a supported Node Version

---

util/npx_verdaccio

*Issue #, if available:* Fix hang on `npm run verdaccio-{browser,node}-{encrypt,decrypt}` for Node >= 20
*Description of changes:* 
Exit on close. 

fix(CI): npx_verdaccio

---

README.md

This Pull Request fixes a typographical error in the README.md file.
- Corrected "to to" to "to" in the README.md file.
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.

chore(README): remove typo

---

.eslintrc.js
.github/workflows/ci.yml
modules/integration-node/src/cli.ts
modules/integration-node/src/integration_tests.ts
package.json
wallaby.conf.js

Adding a CVE-2023-46809 to skip
RSA_PKCS1_OAEP_PADDING test vectors.
Adding a CI target to start node
with --security-revert=CVE-2023-46809
and attempt RSA_PKCS1_OAEP_PADDING test vectors.

fix: Add CVE-2023-46809 option to integration node

---

karma.conf.js

In the SDK credentials.expiration
now needs to be a `Date` object.
See: https://github.com/aws/aws-sdk-js-v3/issues/5890

chore: Fix credentials.expiration

---

.gitignore
modules/integration-node/package.json
modules/integration-node/src/cli.ts
modules/integration-node/src/constants.ts
modules/integration-node/src/get_encrypt_test_iterator.ts
modules/integration-node/src/integration_tests.ts
package-lock.json
package.json

From a given encrypt manifest,
integration-node now takes
`—-decryptManifest` | `-d`
This will create a ziped decrypt manifest
that can be consumed by decrypt.

feat: integration-node can produce decrypt manifests

---

.github/workflows/ci.yml
package-lock.json
package.json

`npm audit fix --force`
This is also going to remove support for NodeJs 16.
The is a BREAKING CHANGE

chore: Update package versions

---

modules/integration-browser/package.json
package.json

`end-of-stream` introduced an unguarded reference to `process` in its patch version update from `1.4.4` to `1.4.5`. ([link](https://github.com/mafintosh/end-of-stream/compare/v1.4.4...v1.4.5))
`process` isn't broadly supported in browser environments, so this change effectively dropped support for browser for many consumers despite being a patch release.
This change: Limit support for `end-of-stream` to max `1.4.4` in our browser integration testing module.
(We don't use this package elsewhere in our browser modules.)

chore(CI): Restrict `end-of-stream` version for browser test vectors
